vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<leader>yy", "\"+y")
vim.keymap.set("v", "<leader>yy", "\"+y")
vim.keymap.set("n", "<leader>pp", "\"+p")
vim.keymap.set("v", "<leader>pp", "\"+p")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<leader>d", "\"_d")
vim.keymap.set("v", "<leader>d", "\"_d")
vim.keymap.set("v", "<leader><", "<Vgv")
vim.keymap.set("v", "<leader>>", ">Vgv")
vim.keymap.set("n", "<leader>fc", function ()
  vim.cmd("%!clang-format")
end)
vim.keymap.set("n", "<leader>tn", function() vim.cmd("tabn") end)
vim.keymap.set("n", "<leader>tp", function() vim.cmd("tabp") end)
vim.keymap.set("n", "<leader>tc", function() vim.cmd("tabc") end)
vim.keymap.set("n", "<leader>bn", function() vim.cmd("bn") end)
vim.keymap.set("n", "<leader>bp", function() vim.cmd("bp") end)
vim.keymap.set("n", "<leader>bc", function() vim.cmd("bd") end)
